language: android

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  licenses:
  - android-sdk-license-.+

before_install:
  - chmod +x .travis/build.sh
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-27" # workaround for accepting the license
  - yes | sdkmanager "platforms;android-P"
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -k $STORE_PASS -in "$PWD/.travis/secrets.tar.enc" -out secrets.tar -d;
      tar xf secrets.tar;
      mv release.keystore "$HOME/.android";
    fi
  #- git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  #- export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script: ".travis/build.sh"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"

deploy:
- provider: releases
  api_key:
    secure: "HfvjHvt4l7A8sgfRYVY8I0/UHQ5lD0Y9R4/75W/UMlzkjJ6pTzC7JzM8s95wQHCPBJtdnr+sQHlZdxYIMZlU4W9qJsWjCRumrQBYwQqe+usjh4Td+4RvdAQb9Lo0O5WaX2pO5dtlHwWimJQl1F1rnzORAktPRQHYIGK9CvLzZrlylh9HdJT8zALK56l0oVK6EXUDPNJ0TsxuegwqB/abJ5eeg
    vA85J16RzO0VVcEtBSJEPmJhl6V2aielhb649vYj9Ol9ic7XUHx8NTzANe4d8lg9Gzvu7rij2GkYAtIjGuP3s6Ixr970xcGKUXyZqapa+J97JiUPrtMgbB9Dxp15I9vT1D6nnb1/xuvl4V8JWHVd8SsQaHMfevtP853BxCb5MNB9gqcqZDNKJXlAH6fDAIGmjwhEN7LRUCI+KR7K2v+kfIRx/2NIxEeBrZ5T
    LkzkJ+iWhy/V/K6Hi86lBNj2iLPVmyKFFAaa+rlbS5Rt1Er1kSXjIvqrkki1XS0vkB8hkrzpJfZL7xJxqihK+3AMB94CWIswKgOr62VOTOAUXYGrm0s2GhY7ke4LiWdBEkUO+xpWOLFMa6+6FROPjIylNAr5jQpNRBLZogpaW2A434dR7Vnay4MSBzN5R9zuOnYLoA4LbzeyomSDqU4cmZnIbk8+es00AiZg
    HZk4lql09U="
  file: kitvei-v*.apk
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: inshiro/Kitvei
    branch: master
    condition: "-z $TRAVIS_TAG"

env:
  global:
  - secure: "gg2Z6DwXg17TMuun7jZLrW5aFlzneqYxQf0+8YRAHAswksqDf56le7J4yKkDaoxKYccXXg974AjflN9xwr2F0fLgsnJRZCjuevNH6pi8skpzVZGmpvdb2wsULtvh/rttd1dsZdMlJF5Ats8QoSCru89A6UJk4Z+nDUM15m2l9V3Yrk6J8a9g65zsvdKojfcmqETfO830QEv5dHbuL0WGt4kYb
    cIi7fMXbVBt60LjO88Dn/OddR+qtBkXSpYfX7vdrrpdKcXNX8qWnpcCqZ7jTfAM2OGksZQHQ/NIsY8vyR3lc5VMFgRmbxf9z9QPaVORnq1SICIWUSjvDRMDVD+Se303XLykcYZCeaD0gM0q5DrsAPdheRv0WdN7rCie56IQLRDHfXjjLdMo8MAvBTrKZWvER5IjAosAiggM8WX0N5v3s+7azsxeF+4YHPRI5
    BQiVGrlYDFrHOv+C33RivB0WGd2K4dF4hDOemXmTaRvZV5hMnoZ1t90uwdNAov8y0ilHyXwBsOTo8MwCnytxH/I4brV7oxOhHUNzjRxknLcAbnnIAHFeyrTFnIiELqL5AQwyhmoDm+m9q6zJvDmvE7LATggc0uxUXYkHhT87FByAWg4SZxW/+K/r6uYU+QwFp6JKXL1gMmw/WalotXnBx1dvVgBAjh6CGxUw
    p/f1qWgmxA="
  - secure: "Y6t+w3nwoQlvqr29QifrXkUP9ir1+R+qzsdfKHWeoh1a8IxsRsxRsKou66sVAvZysizHnWxYi4diVwsrTDmLY1EHQAKMPjsrNBL0YEcpm1l+JJ9iVq49UeKzarlHIOWM2hZkT5dMWIPnIV6cwmTBr7vD8hbkMEj5BTwMBYJXNdoDfj1xnfc0Qv75g1e8Nnru8X2uA7+O//jZy3ZDAf6XZJGWU
    w5U2vHMv/hJUcZ9RwxJfwW/G/z5xlUK8emskQdd+5Vv4eDG1QTFNHJ4nyU4em+cTePnUmlLvMpKF1e0KIk7nP0EyPuRg7J1wy5jvxPH94EWXXKt13FR/TvsrE5CGWmDop77WQTroeDzeZlPfgEs7mFqR3E7ybNxp1NrJ2gzyswkWf7CV8mwMTNckvLZg9H8wXc+PFUBlJcz6GXV+jAYwcxjD1KMqNVhhlKgQ
    ZAZymDVO3IqtTtDPjTAcjJhPwM+4t4rSGsHvOPxgXUaTmi1kfsTyFXlw+jsXCrCrl1TsZTsyC9wbMp/9U7zboDlIY5a6iMHpZqJnnv6bFbSJPe2iaZmbxISK7oTtbHqcSCh/RYcJtnptqNvhSswL8NbkM7aqdlgwbJDQZTTpd2mZ5w4FXGVsZOqc7ao5/uEcrujSf3dA47N+N7A+ruYAlKTVREypoeMIL+0i
    0hgYSqS3KY="
  - secure: "tP9i38Qa59+Hb1n15LvkJGXqOR3/wmv7naO2l7IcAYhIS6/qygs6ElYNz5IylaK+6uJORaHZzXvDzzFHqNMi3WEW34Kx4cHmXWdHN84HjjqDw3Pm3FOpSAaCQsVjPv9XVXOVRy5DGgzQx0VcgMPr2ioCldOFGIMX/UPgAIKpFixkqCXgTVRoqBId5auknQV/O9k9K4RGTGpLpCsa68W8k55yr
    NCrmA/hI3lhrQNUgSpVRbavI5K0os8TvMuQreyH5TALk2t7yia/+O4TVbBG/nU7FQPD2NlzjsMKhYa+tDft1GKuC/7Lte/RN0HCmJDLaboMtsJOP1kmhMOtERacOGqFeMVAMoRMGgPHnmBNSbyV7ltcDJ8pXd1SxzKor159GDC/rno122FuEg0NLRO+vP7XGu+PAHYlMYobFLTOcUURZOGqCh2iwzQga1ARk
    4saUOCt1ZaLPLyKgJ/YFncmXlmY1qrr4Yw9TQQig21yE9rh1oRD6eej41hAQGi4Xn3IuImZNuOKLMz3H8ezkMTpplA3QITWtOeiBDJrjlL/upJd8sQWYGJhR5B/OOp/Ai1QmEcvGF2DhNTf5NmzM4EdxhIOmKl0yauIkVLAV/VmOsqQCnpfCZ5Obe66yQWkZ2KjQLmw/MJTyZE5MlJFIlKres+x3ZZlceUAj
    yug5LFn9Ro="
  - secure: "pEJ0zJkwRF3+3InJ6rro6FIv0tttpEeh9SxPh7izTpmylYL48luYEGNiZ3pK9MbZWwYJ+qz/e7/H0paVTwm0l/lyc/VYNsnWsf4gTdzEjS5rjMfcUmPeb8Ho+DKc8NRMcIVGzgJ2AMGnArC44+FSfpiGnbmRk+boGvHwlnzVfYh8fxGKrpe7KXDry307adymiG5RpjMcPfEIhDqHXMai1yVVX
    TPuh5utMP5NsGEJrDon/cC1bKNBWiXIEGDULrghiqtpcqQj2wYBBc7UxM1bESD4vC3WObGnyV9BWPXq+8DnXoyMS2dTBiDX4fCz0m0qv3sdcXOhzKDSDOWsdxSedApXDi+/8AW0WHYdJ1pg/vsn2z/Y1V/QdAgi/Y9nJBbcrEHX6OrM54yN3oKRqvkwEEvioIvPxe0D3/mMxDcEQ4YwRkQaaq1Rh+C8hbnvu
    xEJQH2Ut1kmKcfnohyYVu8Y7UVIte2hNd5O0lOSMcvqQQFo1y2tK/jQHDgWWaq9L4rNDuuDfm7qMcgn/8WwfmaHxtV+B7s09pDCLVleD0ShGD9YueXn3h/fXj197BtSAbsD9c9Fkcltti5LtMqFPbC6b3PyKhPhMLNxhamv9Mh0TXTBKbGcmzSdYSeS5lA6KCzmy0os2ZGWC9Rv9xmN7LuO8pjoLDs6l8vjO
    AuEEWOJIpM="
